version: "3.3"
services:
        nginx:
                build:
                        context: .
                        dockerfile: requirements/nginx/Dockerfile 
                image: nginx
                container_name: nginx_container
                ports:
                        - "443:443"
                volumes:
                        - wordpress:/volume
                depends_on:
                        - wordpress
                networks:
                        - docker-network
                restart: always
        wordpress:
                build:
                        context: .
                        dockerfile: requirements/wordpress/Dockerfile 
                image: wordpress
                container_name: wordpress_container
                volumes:
                        - wordpress:/volume
                networks:
                        - docker-network
                restart: always
        mariadb:
                build:
                        context: .
                        dockerfile: requirements/mariadb/Dockerfile 
                image: mariadb
                container_name: mariadb_container
                ports:
                        - "3306:3306"
                volumes:
                        - db:/volume
                networks:
                        - docker-network
                environment:
                        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                        MYSQL_USER: ${MYSQL_USER}
                        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                restart: always
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/adamiens/data/wordpress'
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/adamiens/data/db'
networks:
        docker-network:
                driver: bridge
