version: "3.3"
services:
        nginx:
                build:
                        context: .
                        dockerfile: requirements/nginx/Dockerfile 
                image: nginx
                container_name: nginx_container
                ports:
                        - "443:443"
                volumes:
                        - wordpress:/volume
                depends_on:
                        - wordpress
                networks:
                        - docker-network
                restart: always
        wordpress:
                build:
                        context: .
                        dockerfile: requirements/wordpress/Dockerfile 
                image: wordpress
                container_name: wordpress_container
                ports:
                        - "9000:9000"
                volumes:
                        - wordpress:/volume
                depends_on:
                        - mariadb
                networks:
                        - docker-network
                env_file:
                        - .env 
                restart: always
        mariadb:
                build:
                        context: .
                        dockerfile: requirements/mariadb/Dockerfile 
                image: mariadb
                container_name: mariadb_container
                ports:
                        - "3306:3306"
                volumes:
                        - "db:/var/lib/mysql"
                env_file:
                        - .env
                networks:
                        - docker-network
                restart: always
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/armand/data/wordpress'
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/armand/data/db'
networks:
        docker-network:
                driver: bridge

