version: "3.7"
services:
        nginx:
                build: requirements/nginx/
                image: nginx
                container_name: nginx
                ports:
                        - "443:443"
                volumes:
                        - wordpress:/var/www/html
                depends_on:
                        - wordpress
                env_file:
                        - .env 
                networks:
                        - docker-network
                restart: always
        wordpress:
                build: requirements/wordpress/
                image: wordpress
                container_name: wordpress
                volumes:
                        - wordpress:/var/www/html
                depends_on:
                        - mariadb
                        - redis
                networks:
                        - docker-network
                env_file:
                        - .env 
                restart: always
        mariadb:
                build: requirements/mariadb/
                image: mariadb
                container_name: mariadb
                volumes:
                        - "db:/var/lib/mysql"
                env_file:
                        - .env
                networks:
                        - docker-network
                restart: always
        redis:
                build: requirements/bonus/redis/
                image: redis
                container_name: redis
                networks:
                        - docker-network
                restart: always

                #ftp-server:
                #build: requirements/bonus/ftp-server
                #image: ftp-server
                #container_name: ftp-server_container
                #depends_on:
                #        - wordpress
                #volumes:
                #        - shared:/shared
                #ports:
                #        - "21:21"
                #restart: always
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/armand/data/wordpress'
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/armand/data/db'
networks:
        docker-network:
                driver: bridge

