#! /bin/sh

curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
chmod +x wp-cli.phar
mv wp-cli.phar /usr/local/bin/wp

wp core download --path='/volume/wordpress/'

wp config create --path='/volume/wordpress/' --dbname=${WP_DATABASE_NAME} --dbuser=${WP_DATABASE_USR} --dbpass=${WP_DATABASE_PWD} --dbhost=mariadb

wp core install --path='/volume/wordpress' --url="${DOMAIN_NAME}" --title="Inception" --admin_user=${WP_ADMIN_NAME} --admin_password=${WP_ADMIN_PWD} --admin_email=${WP_ADMIN_EMAIL} --skip-email

wp user create --path='/volume/wordpress' ${WP_USER_NAME} ${WP_USER_EMAIL} --role=subscriber --user_pass=${WP_USER_PWD}

wp config --path='/volume/wordpress' set WP_REDIS_HOST "redis"

wp config --path='/volume/wordpress' set WP_REDISPORT "6379"

wp config --path='/volume/wordpress'  set WP_CACHE "true"

#wp config --path='/volume/wordpress' set WP_CACHE_KEY_SALT "${DOMAIN_NAME}"

exec php-fpm8 -F
