#! /bin/sh

#Wordpress installation
wget https://wordpress.org/wordpress-6.2.2.tar.gz -O latest.tar.gz && \
tar xzf latest.tar.gz && rm latest.tar.gz

#Wp-cli installation
wget -O wp-cli.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
chmod +x wp-cli.phar
mv wp-cli.phar /usr/local/bin/wp

cd wordpress
#Database configuration
wp config create --dbname=${WP_DATABASE_NAME} --dbuser=${WP_DATABASE_USR} --dbpass=${WP_DATABASE_PWD} --dbhost=mariadb

wp core install --url="${DOMAIN_NAME}" --title="Inception" --admin_user=${WP_ADMIN_NAME} --admin_password=${WP_ADMIN_PWD} --admin_email=${WP_ADMIN_EMAIL} --skip-email

wp user create ${WP_USER_NAME} ${WP_USER_EMAIL} --role=subscriber --user_pass=${WP_USER_PWD}

#Redis installation
wp  plugin install redis-cache --activate
wp theme install bizboost --activate
wp config set WP_REDIS_HOST "redis"
wp  redis enable --force

#execute php in a foreground
exec php-fpm8 -F
